language: python
python:
  - "2.7"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "pip install coveralls"
script:
  - "./scripts/test.sh"
  - "python setup.py install"
after_success:
  coveralls
