language: python
python:
  - "2.7"
install:
  - "pip install -r requirements/test.txt --use-mirrors"
  - "pip install -e ."
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "pip install coveralls"
script:
  - "python manage.py test"
  - "python setup.py install"
after_success:
  coveralls
